import type { Metadata } from "next";
import { Iceberg } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const font = Iceberg({ weight: "400", subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Console.Dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  );
}
